version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rest_api_db
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    ports:
       - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  redis:
    image: redis:6-alpine

  web:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ""
    volumes:
      - ./app:/backend/app
    ports:
      - 9000:9000
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "alembic upgrade head
      && uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload"

    healthcheck:
      test: ["CMD-SHELL", "alembic upgrade head"]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    build:
      dockerfile: Dockerfile
      context: ""
    command: celery -A app.tasks worker --loglevel INFO --logfile=app/logs/celery.log
    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      web:
        condition: service_healthy
